---
abstract: 'Shared Memory Slices of Bigger Strings'
author:
  - 'Ingy döt Net (ingy) <ingy@cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.36
  ExtUtils::ParseXS: 2.21
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Slice
no_index:
  directory:
    - inc
    - t
requires:
  XSLoader: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
